// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzjmyamhlcpjkajsqksm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56am15YW1obGNwamthanNxa3NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTExMTQsImV4cCI6MjA2NTU2NzExNH0.4pEM0RmG6qZ_q2o-8wZeI6_dUSZ23DGcGrC5f2LbmiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);